### ISSUE TITLE
Pyodide intermittently not loading, causing Run button to not load

### ISSUE THREAD

**Issue by jacobjzhang** [slipHQ/run-wasm#33]
The `pyodide` package intermittently doesn't loading, causing `Run Code` button to not load.

![image](https://user-images.githubusercontent.com/6591285/134605760-a20b9379-c9cc-48ed-b701-c38bec6cf82e.png)

We can either change the logic of the `Run Code` button to load separately from the language dependencies-- probably not advisable since it's useless without it, or have some guarantee/retry for the language package.

**Comment by kennethcassel** [comment]
This might be a good clue for someone looking into fixing this: 

When running locally, getting this issue on first load

![image](https://user-images.githubusercontent.com/22961671/134691231-5bab56fe-696d-40b5-a30d-b377ac8d0200.png)

**Comment by mcintyre94** [comment]
That's weird, those are the changes I made when I updated the example to Pyodide 0.18.1 and they seemed stable!

**Comment by jsjoeio** [comment]
I'm seeing this as well. 

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/134753523-7a2c0218-5952-41f8-85bc-3276671c71a6.png)


## Stack Trace 

```javascript
Uncaught (in promise) TypeError: window.loadPyodide is not a function
    at index-a5183b743b6e8e8b6343.js:1
    at l (main-c4f2541b93e4ae8b71f8.js:1)
    at Generator._invoke (main-c4f2541b93e4ae8b71f8.js:1)
    at Generator.next (main-c4f2541b93e4ae8b71f8.js:1)
    at r (index-a5183b743b6e8e8b6343.js:1)
    at u (index-a5183b743b6e8e8b6343.js:1)
    at index-a5183b743b6e8e8b6343.js:1
    at new Promise (<anonymous>)
    at HTMLScriptElement.<anonymous> (index-a5183b743b6e8e8b6343.js:1)
    at HTMLScriptElement.<anonymous> (main-c4f2541b93e4ae8b71f8.js:1)
```

I don't know if it has to do with AdBlockers or what but when I turn off the shield with Brave, the button appears 🤷🏼‍♂️

**Comment by nikolaystrikhar** [comment]
I can confirm that, but it's not about the browser. 
Yesterday I had a lot of issues with the script loading, about 10% of requests failed, today I tried to sort it out and never had any issue with loading. So my guess is that CDN does not work well.

I also tried to download Brave, but didn't have any issues as well.

@jsjoeio  what do you see in network requests regaring pyodide when it fails?

**Comment by jacobjzhang** [comment]
I took a stab at this, not sure what it is but a few findings:

1) The [indexURL](https://pyodide.org/en/stable/usage/api/js-api.html?highlight=indexURL#globalThis.loadPyodide) appears to be intermittently down:

![image](https://user-images.githubusercontent.com/6591285/134756997-f937cfa0-cb12-4eb0-9ee1-1c0132a97ded.png)

2) It seems we may want [`beforeInteractive`](https://github.com/vercel/next.js/blob/canary/docs/basic-features/script.md) -- "For critical scripts that need to be fetched and executed before the page is interactive" -- seems like we theoretically want the language dependenciess loaded first, but I couldn't get this to work nicely with the `onLoad` callback.

**Comment by mcintyre94** [comment]
@nikolaystrikhar 
> The most interesting moment for now is that I don't see any issues with CDN for now, even when window.loadPyodide is undefined, requests have 200 OK.

That's a big clue! If you're seeing a successful request to the CDN and then that error, then it must be something to do with that code loading that's causing an issue and not the CDN itself.

@jacobjzhang 
> The indexURL appears to be intermittently down:

I think this is probably a red herring, CDNs tend to serve 403 forbidden to any request that isn't a file to prevent attacks. The `indexUrl` is a directory but I suspect that the `loadPyodide` function is actually loading known files from that directory - rather than trying to load the directory itself and hitting the 403.

> It seems we may want beforeInteractive -- "For critical scripts that need to be fetched and executed before the page is interactive" -- seems like we theoretically want the language dependencies loaded first, but I couldn't get this to work nicely with the onLoad callback.

I think this is worth exploring. Assuming the CDN is stable (and AFAIK we have no network errors suggesting it's not) it should be ok to fetch https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pyodide.js before interactive, it's very small and just puts some global state. We could then use `useEffect` instead of `onLoad` to call `loadPyodide` after rendering. My hypothesis is that there's some race condition in the combination of Script + `onLoad`, maybe the fact it's async? That might explain why it's happening on a first load too, if on subsequent ones browser cache is fast enough to paper over it.

FWIW testing NextJS Script + onLoad with a URL that doesn't work, the onLoad never gets called. So I'm pretty sure we can rule out CDN issues here!

**Comment by mcintyre94** [comment]
I've opened a PR with the `beforeInteractive` + `useEffect` approach, the preview is here: https://run-wasm-git-fork-mcintyre94-fix-pyodide-load-sliphq.vercel.app

It'd be great to get as many 👀  as possible on it to make sure nobody's seeing any similar issues with it and that it's still fast.

**Comment by jsjoeio** [comment]
I tested with Brave on my phone just now and it worked!

![Screenshot_20210925-075145](https://user-images.githubusercontent.com/3806031/134775677-a610b719-48e9-4b1c-af3d-e98c2e6ff0fa.png)
